[workspace]
members = [
    "tools/ygen-mc"
]

[workspace.dependencies]
Ygen = { path = "." }

[package]
name = "Ygen"
version = "0.1.0"
edition = "2021"
authors = ["Cr0a3"]

[dependencies]
logos = "0.14.0"
object = { version = "0.36.1", features = ["write"] }
