[workspace]
members = [
    "tools/ygen-mc"
]

[workspace.dependencies]
Ygen = { path = "." }

[package]
name = "Ygen"
version = "0.1.0"
edition = "2021"
authors = ["Cr0a3"]
documentation = "https://toni-graphics.github.io/ygen/Ygen/index.html"
repository = "https://github.com/Toni-Graphics/ygen"
license = "Apache2"
description = "Another code generation libary like LLVM"
categories = ["FFI"]
keywords = ["compiler", "codegen", "llvm"]

[dependencies]
logos = "0.14.0"
object = { version = "0.36.1", features = ["write"] }
