[workspace]
members = [
    "tools/ygen-mc"
]

[workspace.dependencies]
Ygen = { path = "." }

[package]
name = "Ygen"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
object = { version = "0.36.1", features = ["write"] }
once_cell = "1.19.0"
