name: Issue Labeler

on:
  issues:
    types: [opened]

jobs:
  label_assign_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pre
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set variables
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          LABEL_NAME="needs-review"
          ASSIGNEE="Cr0a3"
          COMMENT="Thank you for submiting your issue to ygen! @Cr0a3 will take a look"

      - name: Label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/labels \
            -d "{\"labels\": [\"$LABEL_NAME\"]}"

      - name: Assign user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/assignees \
            -d "{\"assignees\": [\"$ASSIGNEE\"]}"

      - name: Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -d "{\"body\": \"$COMMENT\"}"