name: Ygen rust workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --all
    - name: Run tests
      run: cargo test --all
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.DOC_LLVM_VERSION }}
      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Build Documentation
        run: cargo +nightly doc --features ${{ env.DOC_LLVM_FEATURE }},nightly --verbose --no-deps
      - name: Doc Index Page Redirection
        run: echo '<meta http-equiv="refresh" content="1; url=Ygen/index.html">' > ${{ env.DOC_PATH }}/index.html
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DOC_PATH }}
          force_orphan: true
