name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --all
    - name: Run tests
      run: cargo test --all
    - run: cargo doc
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "target/docs"
