name: Windows/Run Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  ytest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Rust toolchain
        run: 
          rustup update --no-self-update stable

      - name: Install filecheck
        run: 
          pip install filecheck

      - name: Build
        run: cargo build --all

      - name: Run tests
        run: 
          python tools/test.py

      - name: Run rust tests
        run: 
          cargo test --all --features jit
